### ISSUE TITLE
Avoid stop call in runPipeline function

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/testGGIR#1]
@jhmigueles is the `stop()` on line 32 of https://github.com/wadpac/testGGIR/blob/main/R/runPipeline.R#L32 really needed?
It gives an alarming error message when in fact there is no real problem.

Can we replace by `message()`?

**Comment by jhmigueles** [comment]
Hi @vincentvanhees , thanks, I just did it but I went to quick and I commited directly to tha main branch. I should have created a new branch for this but I realized that too late, sorry about that.

Now the `runPipeline` function contains a message instead of an error if this is run for first time, and I included an `else` statement to avoide the comparison part of the pipeline to be run if this is the case.
